CONFIG_LOG=y
CONFIG_THREAD_NAME=y
CONFIG_ASSERT=y

CONFIG_STACK_SENTINEL=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_LOG=y
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_TASK_WDT=y
CONFIG_TASK_WDT_CHANNELS=5
CONFIG_TASK_WDT_HW_FALLBACK=n